spring:
  application:
    name: rent-a-car
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacardb
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      javax.persistence.validation.mode: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml